---
title: "./codemuch"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ex0dus@codemuch.tech
baseurl: ''
url: http://codemuch.tech
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
