---
title: codemuch.tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: https://blog.codemuch.tech
<<<<<<< HEAD
  
=======
enforce_ssl: blog.codemuch.tech
>>>>>>> 6164e6fc0123fdedea3235dbc0ff1533319cc161
email: ex0dus@codemuch.tech
highlighter: rouge
markdown: kramdown
compress_html:
  clippings:
  - html
  - div
  - p
  - ul
  - td
  - h1
  - h2
  - h3
  - h4
  - link
  - meta
  - footer
  - nav
  - img
  - header
  - hr
  - br
  - head
  - style
  - li
  - ul
  - ol
  - time
  - main
  - script
  - title
  comments:
  - "<!-- "
  - " -->"
  endings:
  - all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
  startings: []
sass:
  style: compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
