# Site settings
title: ./codemuch?
header-img: img/home-bg.jpg
email: stack.over.heap@gmail.com
copyright_name: CodeMuch 
description: "Personal site and blog for the teaching and spreading of hacktivism and programming and everything technical"
baseurl: ""
url: "http://ex0dus-0x.github.io"
twitter_username: ex0dus_0x
github_username:  ex0dus-0x
email_username:  stack.over.heap@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

...
name: ./codemuch?
description: Personal blog of hacktivist and programming enthusiast ex0dus.
url: http://ex0dus-0x.github.io
...