---
title: "./codemuch"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  project-static:
    title: Projects
    output: true
heading: Hello, I'm Alan!
email: ex0dus@codemuch.tech
baseurl: ''
markdown: kramdown
kramdown: 
  input: GFM
  syntax_highlighter: rouge
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
